name: unidist
channels:
  - conda-forge
dependencies:
  # for development
  - cloudpickle
  - dask[complete]>=2.22.0
  - distributed>=2.22.0
  - mpi4py>=3.0.3
  - msgpack-python
  - packaging
  - psutil
  - pytest
  # - ray-default
  # for downloading packages from PyPI
  - pip
  - pip:
      # for development
      - ray[default]
      # for building the documentation
      - sphinx
      - sphinx_rtd_theme
      # for code checks
      - black
      - flake8
